### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by KoichiYasuoka** [jiaeyan/Jiayan#1]
Hi, I've just tried to install `jiayan` with
```
pip install jiayan
```
but it failed in compiling `kenlm`. The [pip version of kenlm](https://pypi.org/project/kenlm/) seems very old and did not catch up recent modifications made in the [github version of kenlm](https://github.com/kpu/kenlm). Then, how do I install `jiayan` safely? May I install `kenlm` with
```
pip install https://github.com/kpu/kenlm/archive/master.zip
```
before installing `jiayan`?

**Comment by jiaeyan** [comment]
Hi! Thanks very much for bring up this issue. May I ask what Operating System are you using? I tested the pip version of KenLM on Ubuntu and MacOS, both of them worked fine. If you are using Windows, KenLM is supported only on a contributor basis for now, please see its issues like  [#80](https://github.com/kpu/kenlm/issues/80#issuecomment-280934924) and [#217](https://github.com/kpu/kenlm/issues/217#issuecomment-488992556). I will add notes in the README file.

The pip version of KenLM is indeed not up-to-date though. I will divide the installation of `jiayan` into two steps, one is `pip install jiayan` and another step is `pip install https://github.com/kpu/kenlm/archive/master.zip`, hope them work, thanks!

**Comment by KoichiYasuoka** [comment]
I use Debian 4.9 on my Linux server, and Debian 4.4 through WSL on Windows 10. For old `pip install kenlm` both compilers error at `python/kenlm.cpp` by `exc_type` `exc_value` and `exc_trackback` just as
```
python/kenlm.cpp:6381:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
tstate->exc_traceback = *tb;
        ^~~~~~~~~~~~~
        curexc_traceback
```
However `pip install https://github.com/kpu/kenlm/archive/master.zip` works well, thank you very much for  your cooperation!

**Comment by jiaeyan** [comment]
Great, glad to hear that it works in the `pip install https://github.com/kpu/kenlm/archive/master.zip` way! I have divided the installation procedure into two steps. I will close this issue since it is resolved, thanks!
